-- Consultas Básicas:
SELECT * FROM FUN_FUNCIONARIOS WHERE FUN_NOME = 'Maria';
SELECT * FROM FUN_FUNCIONARIOS WHERE FUN_NOME <> 'Maria';
SELECT * FROM FUN_FUNCIONARIOS WHERE FUN_ID < 100;
SELECT * FROM FUN_FUNCIONARIOS WHERE FUN_DATA_NASCIMENTO > '01/01/2018';
SELECT * FROM FUN_FUNCIONARIOS WHERE FUN_ID <= 100;
SELECT * FROM FUN_FUNCIONARIOS WHERE FUN_DATA_NASCIMENTO >= '01/01/2018';