CREATE TABLE FUN_FUNCIONARIOS2(
	FUN_ID int IDENTITY(1,1) NOT NULL,
	FUN_NOME varchar(20) NOT NULL,
	FUN_SOBRENOME varchar(50) NOT NULL,
	FUN_DATA_NASCIMENTO date NOT NULL,
	FUN_OBSERVACOES text NULL,
 CONSTRAINT PK_FUN_FUNCIONARIOS PRIMARY KEY(FUN_ID)
 );
