-- Cria a tabela para armazenar o ponto dos funcionários:
CREATE TABLE PAC_PONTO_ACESSO
(
    PAC_ID INT IDENTITY(1,1) PRIMARY KEY,
    PAC_DATA_INICIAL DATETIME NOT NULL,
    PAC_DATA_FINAL DATETIME DEFAULT NULL,
    FUN_ID INT NOT NULL
);
-- Adiciona a constraint de foreign key:
ALTER TABLE PAC_PONTO_ACESSO 
ADD CONSTRAINT FK_PAC_PONTOS_ACESSO__FUN_FUNCIONARIOS__FUN_ID
FOREIGN KEY(FUN_ID) REFERENCES FUN_FUNCIONARIOS(FUN_ID);
--

-- Populando a tabela:
INSERT INTO PAC_PONTO_ACESSO
    (PAC_DATA_INICIAL,FUN_ID)
VALUES('30/12/2018 23:08:00', 1);