-- Funções T-SQL:
SELECT FUN_NOME + ' ' + FUN_SOBRENOME,
	   FUN_DATA_NASCIMENTO 
  FROM FUN_FUNCIONARIOS;
--
-- CONCAT:
SELECT CONCAT(FUN_NOME, ' ', FUN_SOBRENOME, ', ', FUN_OBSERVACOES) AS NOME_COMPLETO,
	   FUN_DATA_NASCIMENTO 
  FROM FUN_FUNCIONARIOS;
--
-- CAST:
SELECT FUN_NOME + ' ' + FUN_SOBRENOME + ', ' + CAST(FUN_OBSERVACOES AS varchar) 
  FROM FUN_FUNCIONARIOS;
--
-- IS NULL:
SELECT FUN_NOME + ' ' + FUN_SOBRENOME + ', ' + CAST(ISNULL(FUN_OBSERVACOES, '') AS varchar) 
  FROM FUN_FUNCIONARIOS;
--
-- SQL_VARIANT_PROPERTY:
SELECT SQL_VARIANT_PROPERTY(FUN_NOME + ' ' + FUN_SOBRENOME + ', ' + CAST(ISNULL(FUN_OBSERVACOES, '') AS varchar),'BaseType') AS "NOME_COMPLETO" , 
       FUN_DATA_NASCIMENTO 
  FROM FUN_FUNCIONARIOS;
--
-- TOP:
SELECT TOP 100 FUN_NOME + ' ' + FUN_SOBRENOME + ', ' + CAST(FUN_OBSERVACOES AS varchar) 
  FROM FUN_FUNCIONARIOS;
--
-- YEAR e MONTH:
SELECT CONCAT(FUN_NOME, ' ', FUN_SOBRENOME) AS NOME_COMPLETO, 
       FUN_DATA_NASCIMENTO 
  FROM FUN_FUNCIONARIOS 
 WHERE YEAR(FUN_DATA_NASCIMENTO) = 1980 
   AND MONTH(FUN_DATA_NASCIMENTO) = 06 
    OR MONTH(FUN_DATA_NASCIMENTO) = 02;
--
-- DATEDIFF
SELECT CONCAT(FUN_NOME, ' ', FUN_SOBRENOME) AS NOME_COMPLETO,
	   FUN_DATA_NASCIMENTO 
  FROM FUN_FUNCIONARIOS 
 WHERE DATEDIFF(YEAR, FUN_DATA_NASCIMENTO, GETDATE()) >= 100;
