-- Ordenando os dados
--
-- Ordenação Crescente:
SELECT FUN_NOME, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS ORDER BY FUN_NOME;
-- ou 
SELECT FUN_NOME, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS ORDER BY FUN_NOME ASC;
--
-- Ordenação Decrecente:
SELECT FUN_NOME, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS ORDER BY FUN_NOME DESC;